printWidth: 80
proseWrap: "never"
singleQuote: true
semi: true
arrowParens: "always"
bracketSpacing: true
parser: "babylon"
trailingComma: "all"
overrides:
- files:
  - '*.ts'
  - '*.tsx'
  options:
    parser: typescript
- files: '*.md'
  options:
    parser: markdown
- files: '*.json'
  options:
    parser: json
    printWidth: 80
- files: '*.css'
  options:
    parser: css
