printWidth: 100
proseWrap: always
singleQuote: true
semi: false
arrowParens: "always"
bracketSpacing: true
parser: vue
trailingComma: 'all'
overrides:
- files:
  - '*.ts'
  - '*.tsx'
  options:
    parser: typescript
- files: '*.md'
  options:
    parser: markdown
- files: '*.json'
  options:
    parser: json
    printWidth: 80
- files: '*.css'
  options:
    parser: css
